#!/usr/bin/with-contenv sh

while read events; do rclone rc -q --no-output sync/sync _async=true srcFs="$SOURCE" dstFs="$DESTINATION" "${RC_USER:+--rc-user=$RC_USER}" "${RC_PASS:+--rc-pass=$RC_PASS}" ; done
