#!/usr/bin/with-contenv sh

set --;
if [ -n "$RC_USER" ] && [ -n "$RC_PASS" ] ; then 
  set "$@" -- --rc-user="$RC_USER" --rc-pass="$RC_PASS"; 
fi; 

while read events; do 
  s6-setuidgid abc rclone rc -q --no-output sync/sync _async=false srcFs="$SOURCE" dstFs="$DESTINATION" "$@" ; 
done
