#!/usr/bin/with-contenv sh

#s6-setuidgid abc while true; do find "$FOLDER" | entr -n -d rclone sync; done
s6-setuidgid abc inotifywait -m -r -e close_write -e delete -e move -q $FOLDER | while read events; do rclone sync $SRC $DST ; done
