#!/usr/bin/with-contenv sh

set --; if [ -n "$RC_USER" ] && [ -n "$RC_PASS" ] ; then set "$@" -- --rc_user="$RC_USER" --rc_pass="$RC_PASS"; fi; s6-setuidgid abc rclone rcd -q --rc-addr=0.0.0.0:5572 "$@"
